BusOne02/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account type (e.g. Plan Provider, Network or Specialty Org). Used by MCO and MCO Plan accounts.</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ACO</fullName>
                </value>
                <value>
                    <fullName>Admin Org</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Hospital</fullName>
                </value>
                <value>
                    <fullName>IDN</fullName>
                </value>
                <value>
                    <fullName>MCO</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>PBM</fullName>
                </value>
                <value>
                    <fullName>Plan Provider</fullName>
                </value>
                <value>
                    <fullName>Specialty Org</fullName>
                </value>
                <value>
                    <fullName>Specialty Provider</fullName>
                </value>
                <value>
                    <fullName>Stand-Alone Medicare</fullName>
                </value>
                <value>
                    <fullName>State Medicaid</fullName>
                </value>
                <value>
                    <fullName>Tricare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

BusOne02/src/objects/BOT_Pharmacy_Service__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is Used to store the pharmacy services records and having a lookup relationship with Account.</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Account. SFDC Account ID will be populated here.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pharmacy Services</relationshipLabel>
        <relationshipName>Pharmacy_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_PBM_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Account. SFDC PBM Account ID will be populated here.</description>
        <label>PBM Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pharmacy Services</relationshipLabel>
        <relationshipName>Pharmacy_Services_PBM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pharmacy Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacy Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne02/src/objects/Child_Account_vod__c.object
<CustomObject>
    <description>Describe the hierarchy of accounts and organizations.</description>
    <fields>
        <fullName>Child_Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A reference to the child account in the hierarchical relationship</description>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Of1</relationshipLabel>
        <relationshipName>Child_Account_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A reference to the parent account in the hierarchical relationship</description>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Members1</relationshipLabel>
        <relationshipName>Parent_Account_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Child Account</label>
    <nameField>
        <displayFormat>CA{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_PharmacyServicesTriggerHandlerTest.cls
/*
Name            : BOT_PharmacyServicesTriggerHandlerTest
Created By      : Sreenivasulu A
Created Date    : 21-SEP-2018
Overview        : it is implemented by BusinessOne Technologies Inc.It is a test class of BOT_PharmacyServicesTriggerHandler.
*/
@isTest(seeAllData=false)
private class BOT_PharmacyServicesTriggerHandlerTest 
{
    //Testing while creating a single Pharmacy service record
    static testMethod void createPharmacyService()
    {
        Account objAccount;								//To store an Account record
        Account objPBMAccount;							//To store a PBM Account record
        BOT_Pharmacy_Service__c objPharmacyService;		//To store a Pharmacy service record

        //To create a Pharmacy service record
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(1,'MCO');
        clsTestDataFactory.createPharmacyServices(1,1,1);
        
        //Querying the created test data
        objAccount = [select Id from Account where Account_Type__c = 'MCO'];
        objPBMAccount = [select Id from Account where Account_Type__c = 'PBM'];
        objPharmacyService = [select Id, BOT_Account__c, BOT_PBM_Name__c from BOT_Pharmacy_Service__c];
        
        //Test data validation
        System.assertEquals(objPharmacyService.BOT_Account__c, objAccount.Id);        
        System.assertEquals(objPharmacyService.BOT_PBM_Name__c, objPBMAccount.Id);
        
        //Querying Account plan to PBM linking record which is created by a after insert trigger
        Child_Account_vod__c objChildAccount = [select Id, Parent_Account_vod__c, Child_Account_vod__c from Child_Account_vod__c];
        
        //Test data validation
        System.assertEquals(objChildAccount.Parent_Account_vod__c, objPBMAccount.Id);
        System.assertEquals(objChildAccount.Child_Account_vod__c, objAccount.Id);
    }
    
    //Testing while creating a list of pharmacy service records
    static testMethod void createPharmacyServices()
    {
        List<Account> lstAccount;								//To store a List of Account records
        List<Account> lstPBMAccount;							//To store a List of PBM Account records
        List<BOT_Pharmacy_Service__c> lstPharmacyServices;		//To store a pharmacy services records
        Integer i, j, temp = 0;
        
        //To create a list of Pharmacy service records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(5,'MCO');
        clsTestDataFactory.createPharmacyServices(5,5,10);
        
        //Querying the created test data
        lstAccount = [select Id from Account where Account_Type__c = 'MCO'];
        lstPBMAccount = [select Id from Account where Account_Type__c = 'PBM'];
        lstPharmacyServices = [select Id, BOT_Account__c, BOT_PBM_Name__c from BOT_Pharmacy_Service__c];
        
        //Test data validation
        System.assertEquals(lstAccount.size(), 5);
        System.assertEquals(lstPBMAccount.size(), 5);
        System.assertEquals(lstPharmacyServices.size(), 50);
        for(i = 0; i < 5; i++)
        {
        	for(j = 0; j < 10; j++)
            {
            	System.assertEquals(lstPharmacyServices[temp].BOT_Account__c, lstAccount[i].Id);        
        		System.assertEquals(lstPharmacyServices[temp].BOT_PBM_Name__c, lstPBMAccount[i].Id);
                temp++;
            }
        }
        
        //Querying Account plan to PBM linking records which are created by a after insert trigger
        List<Child_Account_vod__c> lstChildAccount = [select Id, Parent_Account_vod__c, Child_Account_vod__c from Child_Account_vod__c];
        
        //Test data validation
        System.assertEquals(lstChildAccount.size(), 5);
        for(i = 0; i < 5; i++)
        {
            System.assertEquals(lstChildAccount[i].Parent_Account_vod__c, lstPBMAccount[i].Id);
        	System.assertEquals(lstChildAccount[i].Child_Account_vod__c, lstAccount[i].Id);
        }
	}
}