BusOne02/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BOT_Entity_Id__c</fullName>
        <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BusOne02/src/objects/BOT_Drug_Access__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the drug access percentage.</description>
    <fields>
        <fullName>BOT_Access_Percentage__c</fullName>
        <description>Used to store the Access Perchentage</description>
        <label>Access Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>BOT_Drug_Status__c</fullName>
        <description>To store the drug status.</description>
        <label>Drug Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID. It is used for BOT internal reference.</description>
        <label>Entity ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Drug_Rx_Lives__c</fullName>
        <description>Used to store the formulary drug Rx lives.</description>
        <label>Formulary Drug Rx Lives</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Product_ID__c</fullName>
        <description>To store the BOT Formulary Product (Drug) ID. It is used for BOT internal reference.</description>
        <label>Formulary Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Total_Plan_Rx_Lives__c</fullName>
        <description>Used to store the BOT total plan Rx lives</description>
        <label>Total Plan Rx Lives</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Drug Access</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_DrugAccessDashboard_Extn_Test.cls
/*
Name            : BOT_DrugAccessDashboard_Extn_Test
Created date    : 10/03/2018
Created by      : Sreenivasulu Adipudi
Description     : This class is written by BusinessOne Technologies Inc. It is a test class for BOT_DrugAccessDashboard_Extn controller class.
*/
@isTest(seeAllData=false)
private class BOT_DrugAccessDashboard_Extn_Test 
{
    //To test BOT_DrugAccessDashboard_Extn class
    static testMethod void BOT_DrugAccessDashboard_Extn()
    {
        Account objAccount;                           			//To store an Account record
        List<BOT_Drug_Access__c> lstDrugAccess;                 //To create a list of drug access records
        BOT_Drug_Access__c objDrugAccess;						//To create a drug Access record
        List<selectOption> options;                     		//To store a list of markets
        Integer i, j;
        
        //To create a list of Drug access records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(1, 'MCO');
        clsTestDataFactory.createFormularyProductRecords(5);
        //clsTestDataFactory.createDrugAccessRecords(1, 5);
        
        //Creating a list of Drug access records
        lstDrugAccess = new List<BOT_Drug_Access__c>();
        for(i = 0; i < 5; i++)
        {
        	for(j = 0; j < 5; j++)
            {
            	objDrugAccess = new BOT_Drug_Access__c();
            	objDrugAccess.BOT_Entity_ID__c = 0;
            	objDrugAccess.BOT_Formulary_Product_ID__c = i;
            	objDrugAccess.BOT_Total_Plan_Rx_Lives__c = j + 10000;
            	objDrugAccess.BOT_Formulary_Drug_Rx_Lives__c = j + 1000;
            	objDrugAccess.BOT_Access_Percentage__c = j + 90;
            	objDrugAccess.BOT_Drug_Status__c = 'PA';
            	lstDrugAccess.add(objDrugAccess);    
            }
        }
       	insert lstDrugAccess;
        
        //Querying the created test data
        objAccount = [select Id from Account];
        
        //Creating instance for Acccount standard controller class
        ApexPages.StandardController controller = new ApexPages.StandardController(objAccount);
        BOT_DrugAccessDashboard_Extn clsDrugAccessDashbaord = new BOT_DrugAccessDashboard_Extn(controller);
        
        //Calling dynamic list method
        options = clsDrugAccessDashbaord.getDynamicList();
        
        //Test data validation
        System.assertEquals(options.size(), 6);
		System.assertEquals(clsDrugAccessDashbaord.lstDrugAccess.size(), 25);
    }
}