BusOne02/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BOT_Entity_Id__c</fullName>
        <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BusOne02/src/objects/BOT_Drug_Access__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the drug access percentage.</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship to Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Drug Access</relationshipLabel>
        <relationshipName>Drug_Access</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID. It is used for BOT internal reference.</description>
        <label>Entity ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Product_ID__c</fullName>
        <description>To store the BOT Formulary Product (Drug) ID. It is used for BOT internal reference.</description>
        <label>Formulary Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship to formulary product (Drug) object.</description>
        <label>Drug Name</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Drug Access</relationshipLabel>
        <relationshipName>Drug_Access</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Drug Access</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne02/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Formulary_Product_ID__c</fullName>
        <description>It is created by BusiessOne technologies. It is used to store BOT Drug ID.</description>
        <externalId>true</externalId>
        <label>Formulary Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is only used for data loading.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market_vod__c</fullName>
        <description>Market (such as Cholesterol Reducer) that this product belongs to.  This field is used as a filter in the formulary viewer.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Immunology</fullName>
                </value>
                <value>
                    <fullName>Multiple Sclerosis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_DrugAccessTriggerHandler.cls
/*
Name            : BOT_DrugAccessTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 07-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc.It is a helper class to BOT_DrugAccessTrigger trigger and used to populate 
				  the SFDC Account ID and SFDC Formulary Product ID (Drug ID) by comparing BOT Entity ID and BOT Drug ID respectively.

Modified By 	:Harsha BR
Modified date 	:12-SEP-2018
Reason 			:Added comments and modified the code to follow the salesforce standard best practices.
*/

public with sharing class BOT_DrugAccessTriggerHandler 
{
	public static void populateAccountAndProductIds(List<BOT_Drug_Access__c> lstDrugAccess)
    {
        Set<Decimal> setBOTEntityIds = new Set<Decimal>();				// To store the BOT Entity IDs
        Set<String> setBOTFormularyproductIds = new Set<String>();		// To store the Formulary Product IDs
    	Map<Decimal, Id> mapAccountIds;									// Map of BOT Entity ID and its asssociated SFDC Account ID
        Map<String, Formulary_Products_vod__c> mapFormularyProductIds;	// Map of BOT Formulary Product ID and its asssociated SFDC Formulary Product ID
        Formulary_Products_vod__c objFormularyProduct1;					// To store a formulary product record;
        
        //Creating set of BOT entity Ids and set of BOT Formulary Products Ids
        for(BOT_Drug_Access__c objDrugAccess : lstDrugAccess)
        {
       		if(objDrugAccess.BOT_Entity_ID__c != Null && objDrugAccess.BOT_Formulary_Product_ID__c != Null)
            {
            	setBOTEntityIds.add(objDrugAccess.BOT_Entity_ID__c);
            	setBOTFormularyproductIds.add(String.valueOf(objDrugAccess.BOT_Formulary_Product_ID__c));
            }
        }
 		
        //To Retrieve SFDC Accout Ids by comparing BOT Account Ids and put in map 
        mapAccountIds = new Map<Decimal, Id>();
        for(Account objAccount : [select Id, BOT_Entity_ID__c from Account where BOT_Entity_ID__c in : setBOTEntityIds LIMIT 50000])
        {
        	mapAccountIds.put(objAccount.BOT_Entity_ID__c, objAccount.Id);
        }
        
        //Retrieving SFDC Formulary product Id by comparing BOT Formulary Product ID and put in map
        mapFormularyProductIds = new Map<String, Formulary_Products_vod__c>();
        for(Formulary_Products_vod__c objFormularyProduct : [select Id, external_Id_vod__c, market_vod__c from Formulary_Products_vod__c where external_Id_vod__c in : setBOTFormularyproductIds LIMIT 50000])
        {
        	mapFormularyProductIds.put(objFormularyProduct.external_Id_vod__c, objFormularyProduct);    
        }
        
        //Updating BOT_Account__c, BOT_Formulary_Product__c and Name fileds of Drug Access object
        for(BOT_Drug_Access__c objDrugAccess : lstDrugAccess)
        {
            objDrugAccess.BOT_Account__c = mapAccountIds.get(objDrugAccess.BOT_Entity_ID__c);
            objFormularyProduct1 = mapFormularyProductIds.get(String.valueOf(objDrugAccess.BOT_Formulary_Product_ID__c));
            objDrugAccess.BOT_Formulary_Product__c = objFormularyProduct1.Id;
            objDrugAccess.Name = objFormularyProduct1.Market_vod__c;
            //objDrugAccess.BOT_Formulary_Product__c = mapFormularyProductIds.get(String.valueOf(objDrugAccess.BOT_Formulary_Product_ID__c)).Id;
            //objDrugAccess.Name = mapFormularyProductIds.get(String.valueOf(objDrugAccess.BOT_Formulary_Product_ID__c)).Market_vod__c;
        }
    }
}