BusOne02/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account type (e.g. Plan Provider, Network or Specialty Org). Used by MCO and MCO Plan accounts.</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ACO</fullName>
                </value>
                <value>
                    <fullName>Admin Org</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Hospital</fullName>
                </value>
                <value>
                    <fullName>IDN</fullName>
                </value>
                <value>
                    <fullName>MCO</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>PBM</fullName>
                </value>
                <value>
                    <fullName>Plan Provider</fullName>
                </value>
                <value>
                    <fullName>Specialty Org</fullName>
                </value>
                <value>
                    <fullName>Specialty Provider</fullName>
                </value>
                <value>
                    <fullName>Stand-Alone Medicare</fullName>
                </value>
                <value>
                    <fullName>State Medicaid</fullName>
                </value>
                <value>
                    <fullName>Tricare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Entity_Id__c</fullName>
        <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_Level__c</fullName>
        <description>To store the entity level like National / Regional / Local</description>
        <label>Entity Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>State Medicaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

BusOne02/src/objects/BOT_Coverage_Policy__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the coverage policy details and having a lookup relationship with Account.</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to the account object. related account Id will be populated here</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>coverage policy</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Channel__c</fullName>
        <description>For channel selection neither commercial or medicate</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ALL</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store the BOT Entity ID. It is used for BOT internal reference.</description>
        <label>Entity ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Indication__c</fullName>
        <label>Indication</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOT_Score__c</fullName>
        <label>Score</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_AccountSummaryExtnTest.cls
/*
Name            : BOT_AccountSummaryExtn_Test
Created date    : 10/03/2018
Created by      : Sreenivasulu Adipudi
Description     : This class is written by BusinessOne Technologies Inc. It is a test class for BOT_AccountSummary_Extn controller class.
*/
@isTest(seeAllData=false)
private class BOT_AccountSummaryExtnTest 
{
    static testMethod void BOT_AccountSummaryExtn()
    {
        Account objAccount;                         //To create an Account record
        BOT_coverage_policy__c objCoveragePolicy;   //To create a coverage policy record
        
        //Creating an account record
        objAccount = new Account();
        objAccount.Name = 'Test Account Name 1';
        objAccount.BOT_Entity_Id__c = 101;
        objAccount.Account_Type__c = 'Commercial';
        objAccount.BOT_Entity_Level__c = 'National';
        insert objAccount;
        
        //Creating a coverage policy record
        objCoveragePolicy = new BOT_coverage_policy__c();
        objCoveragePolicy.BOT_Account__c = objAccount.Id;
        objCoveragePolicy.BOT_Channel__c = 'Commercial';
        objCoveragePolicy.Name = 'Test Coverage Policy 1';
        objCoveragePolicy.BOT_Score__c = 'Baseline';
        objCoveragePolicy.BOT_Indication__c = 'Biallelic RPE65 Mutation-associated Retinal Dystro';
        insert objCoveragePolicy;

        ApexPages.StandardController controller = new ApexPages.StandardController(objAccount);
        BOT_Account_Summary_Extn clsAccountSummary = new BOT_Account_Summary_Extn(controller);
        
        //Verifiying no of coverage policy records returned form the server
        System.assertEquals(1,clsAccountSummary.lstCoveragePolicy.size());
    }
}