BusOne02/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BOT_Entity_Id__c</fullName>
        <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BusOne02/src/objects/BOT_Thera_Class__c.object
<CustomObject>
    <description>(BOT)It is created by BusinessOne Technologies Inc. It is used to store the Thera class data.</description>
    <fields>
        <fullName>BOT_Specialty_Provider_ID__c</fullName>
        <description>To store the BOT Specialty Provider ID (Entity ID). It is used for BOT internal reference.</description>
        <label>Specialty Provider ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Specialty_Provider__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It is a Lookup relationship to Account (Specialty provider)</description>
        <label>Specialty Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Therapeutic Category</relationshipLabel>
        <relationshipName>Thera_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Thera Class</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Thera Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_TheraClassTriggerHandler.cls
/*
Name            : BOT_TheraClassTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 25-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a helper class of BOT_TheraClassTrigger trigger.
*/

public with sharing class BOT_TheraClassTriggerHandler 
{
	public static void populateSpecialtyProviderIds(List<BOT_Thera_Class__c> lstTheraClass)
    {
    	Set<Decimal> setSpecialtyProviderIds = new Set<Decimal>();			//To store BOT Specialty Provider Ids
        Map<Decimal,Id> mapSpecialtyProviderIds = new Map<Decimal, Id>();	//To store BOT Specialty ProviderId and Salesforce Specialty Provider Id
        
        //Creating a set of BOT SPP Ids
        for(BOT_Thera_Class__c objTheraClass : lstTheraClass)
        {
       		setSpecialtyProviderIds.add(objTheraClass.BOT_Specialty_Provider_ID__c);
        }
        
        //Retrieveing SFDC Account Id by comparing BOT_Entity_Id__c with SPP Id and put it in map
        for(Account objAccount : [select Id, BOT_Entity_Id__c from Account where BOT_Entity_Id__c in : setSpecialtyProviderIds LIMIT 50000])
        {
        	mapSpecialtyProviderIds.put(objAccount.BOT_Entity_Id__c, objAccount.Id);
        }
        
       	//Updating BOT_Specialty_Provider__c field with SFDC Account Id
        for(BOT_Thera_Class__c objTheraClass : lstTheraClass)
        {
            objTheraClass.BOT_Specialty_Provider__c = mapSpecialtyProviderIds.get(objTheraClass.BOT_Specialty_Provider_ID__c);
        }    
    }
}