BusOne02/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BOT_Entity_Id__c</fullName>
        <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
        <externalId>true</externalId>
        <label>Entity Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BusOne02/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that this Benefit Design belongs to.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Entity_ID__c</fullName>
        <description>To store BOT Entity ID. It is used for BOT internal reference.</description>
        <label>Entity ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Name__c</fullName>
        <description>Used to store the name of Formulary</description>
        <label>Formulary Name Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_vod__c</fullName>
        <description>The value in the type field (Commercial, VA, Medicaid, etc.) is cascaded down to the Benefit Design Lines and controls what Status and Restrictions are valid. If this type field is changed, it will cascade down to the Benefit Design Lines.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Medicaid</fullName>
                </value>
                <value>
                    <fullName>PBM-Commercial</fullName>
                </value>
                <value>
                    <fullName>PBM-Medicare</fullName>
                </value>
                <value>
                    <fullName>State Medicaid</fullName>
                </value>
                <value>
                    <fullName>Tricare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Formulary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_BenefitDesignTriggerHandler.cls
/*
Name			: BOT_BenefitDesignTriggerHandler
Created By		: Sreenivasulu A
Created Date	: 28-AUG-2018
Overview		: This class is written by BusinessOne Technologies Inc. It performs below functionalities:-
				1.	It is used to truncate the name of the Benefit Design if the characters is more than 80. Append the channel at the end of the name.
				2.	It is used to populate the parent SFDC ID by using BOT Entity ID.
*/
public with sharing class BOT_BenefitDesignTriggerHandler 
{
	public static void manageNameAndPopulateAccountId(List<Benefit_Design_vod__c> lstBenefitDesign, Set<Decimal> setAccountIds)
    {
        Integer channelLength = 0;									//To store length of channel value
        Map<Decimal, ID> mapAccountIds = new Map<Decimal, ID>();	//To store BOT Entity Ids and SFDC Ids of Account object
        
        //To Retrieve SFDC Account Ids by comparing BOT Entity Ids and put in map
        for(Account objAccount : [SELECT Id, BOT_Entity_ID__c FROM Account WHERE BOT_Entity_ID__c in : setAccountIds])
        {
            mapAccountIds.put(objAccount.BOT_Entity_ID__c, objAccount.Id);
        }
		
        for(Benefit_Design_vod__c objBenefitDesign : lstBenefitDesign)
        {
            //To update related SFDC Account ID
            objBenefitDesign.Account_vod__c = mapAccountIds.get(objBenefitDesign.BOT_Entity_ID__c);
            
            //To handle name field
            if(objBenefitDesign.BOT_Formulary_Name__c != Null && objBenefitDesign.Type_vod__c != Null)
            {
                //To append ' - ' and channel to the BOT_Formulary_Name field make channelLength as 80 - (3 + channel value length)
                channelLength = 77 - objBenefitDesign.Type_vod__c.length();
                
                //Check weather BOT_Formulary_Name field value length is lessthan or equal to channelLength
                //If it is true then append channel to BOT_Formulary_Name field value and store it in name field
                if(objBenefitDesign.BOT_Formulary_Name__c.length() <= channelLength)
                {
                	objBenefitDesign.Name = objBenefitDesign.BOT_Formulary_Name__c + ' - '+ objBenefitDesign.Type_vod__c;   
                }
                
                //If name field more than channelLength trim the BOT_Formulary_Name field value
                //Append '.. - ' + channel to BOT_Formulary_Name field value and store it in name field 
                else
                {
                    channelLength = channelLength - 2;
                	objBenefitDesign.Name = objBenefitDesign.BOT_Formulary_Name__c.subString(0,channelLength) + '.. - '+ objBenefitDesign.Type_vod__c;  
                }
            }
        }
    }
}