BusOne02/src/objects/Benefit_Design_Line_vod__c.object
<CustomObject>
    <description>A Benefit Design Line is a child of a Benefit Design. It represents the formulary information for one product for a specific benefit design.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>To store the BOT Formulary ID. It is used for BOT internal reference.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Product_ID__c</fullName>
        <description>To store the BOT Drug Id. It is used for BOT internal reference.</description>
        <label>Formulary Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Benefit_Design_vod__c</fullName>
        <description>Link to the parent Benefit Design.</description>
        <label>Benefit Design</label>
        <referenceTo>Benefit_Design_vod__c</referenceTo>
        <relationshipLabel>Benefit Design Lines</relationshipLabel>
        <relationshipName>Benefit_Design_Line_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Copay_Source_vod__c</fullName>
        <description>Copay (Source) value for this benefit design line.</description>
        <label>Copay (Source)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes_Source_vod__c</fullName>
        <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Notes field is filled in, it will override the Notes (Source) field in the display of the formulary control.</description>
        <label>Notes (Source)</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Restrictions_Source_vod__c</fullName>
        <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Restrictions field is filled in, it will override the Restrictions (Source) field in the display of the formulary control.</description>
        <label>Restrictions (Source)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>QL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Source_vod__c</fullName>
        <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Status field is filled in, it will override the Status (Source) field in the display of the formulary control.</description>
        <label>Status (Source)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Non-Preferred</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Preferred</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Design Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Linenumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is created by BusinessOne Technologies. It is used to store BOT Formulary ID.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Formulary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_BenefitDesignLine_Extn_Test.cls
/*
Name            : BOT_BenefitDesignLine_Extn_Test
Created date    : 29/08/2018
Created by      : Sreenivasulu Adipudi
Description     : This class is written by BusinessOne Technologies Inc. It is test class for BOT_BenefitDesignLine_Extn class.
*/
@isTest(seeAllData=false)
private class BOT_BenefitDesignLine_Extn_Test
{
    //Testing BOT_BenefitDesignLine_Extn standard controller class
    static testMethod void BOT_BenefitDesignLine_Extn()
    {
        Benefit_Design_vod__c objBenefitDesign;           		//To store a Benefit design record
        Benefit_Design_Line_vod__c objBenefitDesignLine;  		//To store a Benefit design line record
        List<Benefit_Design_Line_vod__c> lstBenefitDesignLine;	//To store a list if Benefit design records
        List<selectOption> options;                             //To store a list of markets
        Integer i, j, temp = 0;
        
        //To create a Benefit design Line record
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(1,'MCO');
        clsTestDataFactory.createBenefitDesignRecords(1,1,'Commercial');
        clsTestDataFactory.createFormularyProductRecords(5);
        //clsTestDataFactory.createBenefitDesignLineRecords(5,5);
        
        //Creating a list of benefit design line records
        lstBenefitDesignLine = new List<Benefit_Design_Line_vod__c>();
        for(i = 0; i < 5; i++)
        {
            for(j = 0; j < 5; j++)
			{
				objBenefitDesignLine = new Benefit_Design_Line_vod__c();
            	objBenefitDesignLine.BOT_Benefit_Design_ID__c = 0;
            	objBenefitDesignLine.BOT_Formulary_Product_ID__c = i;
            	objBenefitDesignLine.Status_Source_vod__c = 'Test Status 1';
            	objBenefitDesignLine.Restrictions_Source_vod__c = 'PA';
				objBenefitDesignLine.Notes_Source_vod__c = 'Test Notes';
            	objBenefitDesignLine.Copay_Source_vod__c = '$10 - $20';
            	lstBenefitDesignLine.add(objBenefitDesignLine);
			}
        }
        insert lstBenefitDesignLine;
        
        //Querying the created test data
        objBenefitDesign = [SELECT Id FROM Benefit_Design_vod__c];
        
        //Creating instance for Benefit design standard controller class
        ApexPages.StandardController controller = new ApexPages.StandardController(objBenefitDesign);
        BOT_BenefitDesignLine_Extn clsBenefitDesignLine= new BOT_BenefitDesignLine_Extn(controller);
        
        //Calling dynamic list method
        options = clsBenefitDesignLine.getDynamicList();
       
        //Test data validation
        System.assertEquals(options.size(), 7);
        System.assertEquals(clsBenefitDesignLine.lstBenefitDesignLine.size(), 25);
        
        //Calling marketFilterRetrieve method with selected market as 'Market 1'
        clsBenefitDesignLine.selectedMarket = 'Test Market 1';
        clsBenefitDesignLine.marketFilterRetrieve();
        System.assertEquals(clsBenefitDesignLine.lstBenefitDesignLine.size(), 5);
        
        //Calling marketFilterRetrieve method with selected market as '--ALL-'
        clsBenefitDesignLine.selectedMarket = '--ALL--';
        clsBenefitDesignLine.marketFilterRetrieve();
        System.assertEquals(clsBenefitDesignLine.lstBenefitDesignLine.size(), 25);
        
        //Calling marketFilterRetrieve method with selected market as 'All Company Products'
        clsBenefitDesignLine.selectedMarket = 'All Company Products';
        clsBenefitDesignLine.marketFilterRetrieve();
        System.assertEquals(clsBenefitDesignLine.lstBenefitDesignLine.size(), 25);
    }
}