BusOne02/src/objects/Benefit_Design_Line_vod__c.object
<CustomObject>
    <description>A Benefit Design Line is a child of a Benefit Design. It represents the formulary information for one product for a specific benefit design.</description>
    <fields>
        <fullName>BOT_Plan_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Plan product.</description>
        <label>Plan Product</label>
        <referenceTo>BOT_Plan_Product__c</referenceTo>
        <relationshipLabel>Benefit Design</relationshipLabel>
        <relationshipName>Plan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Product_Formulary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to product formulary junction object</description>
        <label>Product Formulary</label>
        <referenceTo>BOT_Product_Formulary_JO__c</referenceTo>
        <relationshipLabel>Benefit Design Line</relationshipLabel>
        <relationshipName>Product_Formulary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Design_vod__c</fullName>
        <description>Link to the parent Benefit Design.</description>
        <label>Benefit Design</label>
        <referenceTo>Benefit_Design_vod__c</referenceTo>
        <relationshipLabel>Benefit Design Lines</relationshipLabel>
        <relationshipName>Benefit_Design_Line_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Benefit Design Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Linenumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <label>Benefit Design</label>
    <nameField>
        <label>Formulary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/objects/BOT_Plan_Product__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the Plan product information and having a lookup relationship with Account.</description>
    <label>Plan Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/objects/BOT_Product_Formulary_JO__c.object
<CustomObject>
    <description>(BOT) It is a junction object between plan product and formulary objects. It is having Master-Detail relationship with Plan product and Plan formulary objects.</description>
    <fields>
        <fullName>BOT_Plan_Product_ID__c</fullName>
        <description>It is used to store the plan product ID. It is used for BOT internal reference only.</description>
        <label>Plan Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product__c</fullName>
        <description>Master-Detail relationship to Plan product object</description>
        <label>Plan Product</label>
        <referenceTo>BOT_Plan_Product__c</referenceTo>
        <relationshipLabel>Plan Product</relationshipLabel>
        <relationshipName>Plan_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Formulary</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>S No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Formulary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_PopulateProductFormularyID.cls
/*
Name         : BOT_PopulateProductFormularyID
Created By   : Harsha BR 
Created Date : 11-AUG-2018
Overview     :This class is written by BusinessOne Technologies Inc.It used to populate the Product Formulary Id on the Benefit Design Line
*/
public class BOT_PopulateProductFormularyID {
    
    /*
    Public static void updateProductformulary(List<Benefit_Design_Line_vod__c> lstBDLines)
    {
        Set<ID> setPlanProductIDs = new set<ID>();
        Set<ID> setFormularyIDs = new set<ID>();
       
        for(Benefit_Design_Line_vod__c objBDL : lstBDLines)
        {
            if(objBDL.BOT_Plan_Product__c!=null)
            {
                setPlanProductIDs.add(objBDL.BOT_Plan_Product__c);      
            }
            
            if(objBDL.Benefit_Design_vod__c!=null)
            {
                setFormularyIDs.add(objBDL.Benefit_Design_vod__c);   
            }   
        }
        
        List<BOT_Product_Formulary_JO__c> lstProductFormularies = [SELECT Id, BOT_Formulary_ID__c, BOT_Plan_Product_ID__c
                                                                   FROM BOT_Product_Formulary_JO__c 
                                                                   WHERE BOT_Formulary_ID__c in : setFormularyIDs AND BOT_Plan_Product_ID__c in : setPlanProductIDs
                                                                   LIMIT 50000];
        
        for(Benefit_Design_Line_vod__c objBDL : lstBDLines)
        {
            for(BOT_Product_Formulary_JO__c objPF : lstProductFormularies)
            {
                if(objBDL.BOT_Plan_Product__c == objPF.BOT_Plan_Product_ID__c && objBDL.Benefit_Design_vod__c == objPF.BOT_Formulary_ID__c)
                {
                    objBDL.BOT_Product_Formulary__c = objPF.id;
                }
            }   
        } 
    }
       */
}