BusOne02/src/objects/Benefit_Design_Line_vod__c.object
<CustomObject>
    <description>A Benefit Design Line is a child of a Benefit Design. It represents the formulary information for one product for a specific benefit design.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>To store the BOT Formulary ID. It is used for BOT internal reference.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Formulary_Product_ID__c</fullName>
        <description>To store the BOT Drug Id. It is used for BOT internal reference.</description>
        <label>Formulary Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Benefit_Design_vod__c</fullName>
        <description>Link to the parent Benefit Design.</description>
        <label>Benefit Design</label>
        <referenceTo>Benefit_Design_vod__c</referenceTo>
        <relationshipLabel>Benefit Design Lines</relationshipLabel>
        <relationshipName>Benefit_Design_Line_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is used for data loading only.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product is a lookup the Formulary Product object. Note that this is not a lookup to the product catalog that is used for sampling and detailing.  This field is required because every benefit design line relates to a product.</description>
        <label>Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Benefit Design Lines</relationshipLabel>
        <relationshipName>Product_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Benefit Design Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Linenumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is created by BusinessOne Technologies. It is used to store BOT Formulary ID.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is used only for data loading.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Formulary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>BOT_Formulary_Product_ID__c</fullName>
        <description>It is created by BusiessOne technologies. It is used to store BOT Drug ID.</description>
        <externalId>true</externalId>
        <label>Formulary Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is only used for data loading.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/objects/Product_vod__c.object
<CustomObject>
    <description>The Product Catalog</description>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is used only for data loading.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Product Catalog</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_BenefitDesignLineTriggerHandler.cls
/*
Name            : BOT_BenefitDesignLineTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 07-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc.It is used to populate the SFDC Benefit Design ID (plan formulary ID) and SFDC Formulary Product ID (Drug ID) 
				  by using BOT Formulary ID and BOT Drug ID respectively.

Modified By 	:Harsha BR
Modified date 	:14-SEP-2018
Reason 			:Added comments and modified the code to follow the salesforce standard best practices.
*/

public with sharing class BOT_BenefitDesignLineTriggerHandler 
{
	public static void populateBenefitDesignAndProductIds(List<Benefit_Design_Line_vod__c> lstBenefitDesignLine, Set<String> setBOTBenefitDesignIds, Set<String> setBOTFormularyproductIds)
    {
        Map<String, Id> mapBenefitDesignIds = new Map<String, Id>();		//Map of BOT Benefit design Ids and asssociated SFDC Benefit Design IDs
        Map<String, Id> mapFormularyProductIds = new Map<String, Id>();	//Map of BOT Formulary product Ids and asssociated SFDC Formulary product IDs
        
        //To Retrieve SFDC Benefit design Id by comparing BOT Benefit design Id and put in map   
        for(Benefit_Design_vod__c objBenefitDesign : [select Id, external_Id_vod__c from Benefit_Design_vod__c where external_Id_vod__c in : setBOTBenefitDesignIds])
        {
        	mapBenefitDesignIds.put(objBenefitDesign.external_Id_vod__c, objBenefitDesign.Id);
        }
        
        //To Retrieve SFDC Formulary product Id by comparing BOT Formulary product Id ID and put in map
        for(Formulary_Products_vod__c objFormularyProduct : [select Id, external_Id_vod__c from Formulary_Products_vod__c where external_Id_vod__c in : setBOTFormularyproductIds])
        {
        	mapFormularyProductIds.put(objFormularyProduct.external_Id_vod__c, objFormularyProduct.Id);
        }
        
        //Updating Benefit_Design_vod__c and Product_vod__c fileds
        for(Benefit_Design_Line_vod__c objBenefitDesignLine : lstBenefitDesignLine)
        {
            objBenefitDesignLine.Benefit_Design_vod__c = mapBenefitDesignIds.get(String.valueOf(objBenefitDesignLine.BOT_Benefit_Design_ID__c));
            objBenefitDesignLine.Product_vod__c = mapFormularyProductIds.get(String.valueOf(objBenefitDesignLine.BOT_Formulary_Product_ID__c));
 		}
    }
}