BusOne02/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is created by BusinessOne Technologies. It is used to store BOT Formulary ID.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is used only for data loading.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <label>Formulary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/objects/BOT_Plan_Product__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the Plan product information and having a lookup relationship with Account.</description>
    <fields>
        <fullName>BOT_Product_ID__c</fullName>
        <description>To store BOT Product ID. This field is used as external ID</description>
        <externalId>true</externalId>
        <label>Product ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Plan Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/objects/BOT_Product_Formulary_JO__c.object
<CustomObject>
    <description>(BOT) It is a junction object between plan product and formulary objects. It is having Master-Detail relationship with Plan product and Plan formulary objects.</description>
    <fields>
        <fullName>BOT_Benefit_Design_ID__c</fullName>
        <description>It is used to store the BOT formulary ID. It is used for BOT internal reference only.</description>
        <label>Benefit Design ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Benefit_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Benefit Design Object.</description>
        <label>Benefit Design</label>
        <referenceTo>Benefit_Design_vod__c</referenceTo>
        <relationshipLabel>Benefit Design</relationshipLabel>
        <relationshipName>Benefit_Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product_ID__c</fullName>
        <description>It is used to store the plan product ID. It is used for BOT internal reference only.</description>
        <label>Plan Product ID</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BOT_Plan_Product__c</fullName>
        <description>Master-Detail relationship to Plan product object</description>
        <label>Plan Product</label>
        <referenceTo>BOT_Plan_Product__c</referenceTo>
        <relationshipLabel>Plan Product</relationshipLabel>
        <relationshipName>Plan_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Formulary</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>S No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Formulary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_ProductFormularyTriggerHandler.cls
/*
Name			: BOT_ProductFormularyTriggerHandler
Created by		: Sreenivasulu Adipudi
Created date	: 05-nov-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a helper class for BOT_ProductFormularyTrigger trigger.
*/
public with sharing class BOT_ProductFormularyTriggerHandler
{
	public static void populateProductIdAndFormularyId(List<BOT_Product_Formulary_JO__c> lstProductFormulary)
    {
    	set<String> setPlanProductIds = new set<String>();
        set<String> setBenefitDesignIds = new set<String>();
        Map<String, ID> mapPlanProductIds = new Map<String, ID>(); 
        Map<String, ID> mapBenefitDesignIds = new Map<String, ID>();
        for(BOT_Product_Formulary_JO__c objProductFormulary : lstProductFormulary)
        {
			if(objProductFormulary.BOT_Plan_Product_ID__c != null)
            {
            	setPlanProductIds.add(String.valueOf(objProductFormulary.BOT_Plan_Product_ID__c));
            }
            if(objProductFormulary.BOT_Benefit_Design_ID__c != null)
            {
				setBenefitDesignIds.add(String.valueOf(objProductFormulary.BOT_Benefit_Design_ID__c));
            }
        }
            
        for(BOT_Plan_Product__c objPlanProduct : [select Id, BOT_Product_ID__c from BOT_Plan_Product__c where BOT_Product_ID__c in : setPlanProductIds])
        {
        	mapPlanProductIds.put(objPlanProduct.BOT_Product_ID__c, objPlanProduct.Id);
        }
        
        for(Benefit_Design_vod__c objBenefitDesign : [select Id, External_ID_vod__c from Benefit_Design_vod__c where External_ID_vod__c in : setBenefitDesignIds])
        {
        	mapBenefitDesignIds.put(objBenefitDesign.External_ID_vod__c, objBenefitDesign.Id);
        }
        
        for(BOT_Product_Formulary_JO__c objProductFormulary : lstProductFormulary)
        {
            if(objProductFormulary.BOT_Plan_Product_ID__c != null)
            {
            	objProductFormulary.BOT_Plan_Product__c = mapPlanProductIds.get(String.valueOf(objProductFormulary.BOT_Plan_Product_ID__c));
            }
            if(objProductFormulary.BOT_Benefit_Design_ID__c != null)
            {
				objProductFormulary.BOT_Benefit_Design__c = mapBenefitDesignIds.get(String.valueOf(objProductFormulary.BOT_Benefit_Design_ID__c));
            }
        }
    }
}