BusOne02/src/objects/Benefit_Design_Line_vod__c.object
<CustomObject>
    <description>A Benefit Design Line is a child of a Benefit Design. It represents the formulary information for one product for a specific benefit design.</description>
    <fields>
        <fullName>Benefit_Design_vod__c</fullName>
        <description>Link to the parent Benefit Design.</description>
        <label>Benefit Design</label>
        <referenceTo>Benefit_Design_vod__c</referenceTo>
        <relationshipLabel>Benefit Design Lines</relationshipLabel>
        <relationshipName>Benefit_Design_Line_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competitor_vod__c</fullName>
        <description>Indicates whether the product is a competitor product. If true, product is a competitor; otherwise it is a company product. Evaluated from the Competitor_vod field in Formulary_Product_vod object. Not visible in the page layout - used only by the application.</description>
        <formula>Product_vod__r.Competitor_vod__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Competitor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Copay_Source_vod__c</fullName>
        <description>Copay (Source) value for this benefit design line.</description>
        <label>Copay (Source)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes_Source_vod__c</fullName>
        <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Notes field is filled in, it will override the Notes (Source) field in the display of the formulary control.</description>
        <label>Notes (Source)</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product is a lookup the Formulary Product object. Note that this is not a lookup to the product catalog that is used for sampling and detailing.  This field is required because every benefit design line relates to a product.</description>
        <label>Product</label>
        <referenceTo>Formulary_Products_vod__c</referenceTo>
        <relationshipLabel>Benefit Design Lines</relationshipLabel>
        <relationshipName>Product_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Restrictions_Source_vod__c</fullName>
        <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Restrictions field is filled in, it will override the Restrictions (Source) field in the display of the formulary control.</description>
        <label>Restrictions (Source)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>QL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Source_vod__c</fullName>
        <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Status field is filled in, it will override the Status (Source) field in the display of the formulary control.</description>
        <label>Status (Source)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Covered</fullName>
                </value>
                <value>
                    <fullName>Non-Preferred</fullName>
                </value>
                <value>
                    <fullName>Not Covered</fullName>
                </value>
                <value>
                    <fullName>Preferred</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Design Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Linenumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BusOne02/src/objects/Benefit_Design_vod__c.object
<CustomObject>
    <description>Benefit Design represents a Benefit Design for a specific Managed Care (Payer) account. There may be multiple Benefit Designs for a particular account. Benefit Design Line is a child object of Benefit Design.</description>
    <label>Benefit Design</label>
    <nameField>
        <label>Formulary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <fields>
        <fullName>Competitor_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product belongs to a competitor. If not, the product is assumed to be a company product and shows up in bold in the formulary viewer.</description>
        <label>Competitor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_vod__c</fullName>
        <description>Market (such as Cholesterol Reducer) that this product belongs to.  This field is used as a filter in the formulary viewer.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Immunology</fullName>
                </value>
                <value>
                    <fullName>Multiple Sclerosis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Formulary Product</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_BenefitDesignLine_Extn.cls
/*
Name            : BOT_BenefitDesignLine_Extn
Created date    : 28/08/2018
Created by      : Sreenivasulu Adipudi
Description     : This class is written by BusinessOne Technologies Inc. It is an extension for BOT_BenefitDesignLine_View Visualforce page.
*/
public with sharing class BOT_BenefitDesignLine_Extn 
{
    ID benefitDesignID;                                                         //To store the current record ID
    public string selectedMarket {get;set;}                        				//To store user selected maket from dropdown
    public List<Benefit_Design_Line_vod__c> lstBenefitDesignLine {get;set;}     //To store list of benefit design line records
    set<String> setMarkets = new set<String>();                          		//To store uniquee market values
    public Integer setMarketsSize {get;set;}
    
    //Controller
    public BOT_BenefitDesignLine_Extn(ApexPages.StandardController controller)
    {
        benefitDesignID = controller.getId();
        //To get list of benefit design records associated with selected formulary
        lstBenefitDesignLine = [SELECT Id, Product_vod__r.Market_vod__c FROM Benefit_Design_Line_vod__c WHERE Benefit_Design_vod__c =: benefitDesignID 
                                ORDER BY Product_vod__r.Name LIMIT 50000];
        
        if(lstBenefitDesignLine != Null)
        {
            for(Benefit_Design_Line_vod__c objBenefitDesignLine : lstBenefitDesignLine)
            {
                if(objBenefitDesignLine.Product_vod__r.Market_vod__c != Null)
                {
                    //A set collection is used to eliminate repeated market values
                    setMarkets.add(objBenefitDesignLine.Product_vod__r.Market_vod__c);    
                }
            }
            setMarketsSize = setMarkets.size();
			selectedMarket = 'Immunology';
        	//To get list of benefit design records associated with selected formulary
        	marketFilterRetrieve();
        }
    }
    
 	//To get list of benefit design records associated with selected formulary and selected market
    public void marketFilterRetrieve()
    {
        if(selectedMarket == '--ALL--' || selectedMarket == Null)
        {
            //initialRetrieve();    
            lstBenefitDesignLine = [SELECT Id, Product_vod__r.Market_vod__c, Product_vod__r.Name, Status_Source_vod__c, Restrictions_Source_vod__c, Copay_Source_vod__c, Notes_Source_vod__c 
                                FROM Benefit_Design_Line_vod__c 
                                WHERE Benefit_Design_vod__c =: benefitDesignID 
                                ORDER BY Product_vod__r.Name 
                                LIMIT 50000];
        }
        else if(selectedMarket == 'All Company Products')
        {
        	lstBenefitDesignLine = [SELECT Id, Product_vod__r.Market_vod__c, Product_vod__r.Name, Status_Source_vod__c, Restrictions_Source_vod__c, Copay_Source_vod__c, Notes_Source_vod__c 
                                	FROM Benefit_Design_Line_vod__c 
                                	WHERE Benefit_Design_vod__c =: benefitDesignID AND Competitor_vod__c = false
                                	ORDER BY Product_vod__r.Name 
                                	LIMIT 50000];   
        }
        else
        {
            lstBenefitDesignLine = [SELECT Id, Product_vod__r.Market_vod__c, Product_vod__r.Name, Status_Source_vod__c, Restrictions_Source_vod__c, Copay_Source_vod__c, Notes_Source_vod__c 
                                    FROM Benefit_Design_Line_vod__c 
                                    WHERE Benefit_Design_vod__c =: benefitDesignID AND Product_vod__r.Market_vod__c =: selectedMarket
                                    ORDER BY Product_vod__r.Name 
                                    LIMIT 50000];    
        }
    }
    
    //To create dynamic picklist with market values
    public List<selectOption> getDynamicList()
    {
        List<selectOption> options = new List<selectOption>();
        if(setMarketsSize > 0 && setMarkets != null)
        {
            if(setMarketsSize > 1)
            {
                options.add(new selectOption('--ALL--','--ALL--'));
                options.add(new selectOption('All Company Products','All Company Products'));
            }
            for(String m : setMarkets)
            {
                options.add(new selectOption(m,m));
            }
            options.sort();
        }
        return options;
    }    
}