BusOne02/src/objects/BOT_Coverage_Policy__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the coverage policy details and having a lookup relationship with Account.</description>
    <fields>
        <fullName>Test1__c</fullName>
        <label>Test1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_CoveragePolicyViewExtn.cls
/*
Name : BOT_CoveragePolicyViewExtn
Created Date : 22-Nov-2018
Created By : Harsha BR
*/
public class BOT_CoveragePolicyViewExtn
{   
    ID coveragePolicyId;
    Public String strRichText{get;set;}
    Public String strRichText1{get;set;}
    Public BOT_CoveragePolicyViewExtn(ApexPages.StandardController controller)
    {
     	coveragePolicyId = controller.getId();
        List<BOT_Coverage_Policy__c> lstCoveragePolicy=[SELECT Id,Test__c,Test1__c
                                                        FROM BOT_Coverage_Policy__c
                                                        WHERE ID=:coveragePolicyId
                                                        LIMIT 1];
        strRichText=lstCoveragePolicy[0].Test__c.replace('*','<br>');
        system.debug('***Before strRichText***'+strRichText);
        strRichText=strRichText.replace('>>', '<ul><li>');
        strRichText=strRichText.replace('|', '</li><li>');
        strRichText=strRichText.replace('<<', '</ul></li>');
        system.debug('***After strRichText***'+strRichText);
        
         strRichText1=lstCoveragePolicy[0].Test1__c.replace('*','<br>');
        system.debug('***Before strRichText1***'+strRichText1);
        strRichText1=strRichText1.replace('>>', '<ul><li>');
        strRichText1=strRichText1.replace('|', '</li><li>');
        strRichText1=strRichText1.replace('<<', '</ul></li>');
        system.debug('***After strRichText1***'+strRichText1);     
    }
}