BusOne02/src/objects/BOT_Drug_Access__c.object
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the drug access percentage.</description>
    <fields>
        <fullName>BOT_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship to Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Drug Access</relationshipLabel>
        <relationshipName>Drug_Access</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Drug Access</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BusOne02/src/objects/Formulary_Products_vod__c.object
<CustomObject>
    <description>To display products in the formulary viewer, they must be entered into Formulary Product. Formulary product is referred to by Benefit Design Lines. Formulary product must be loaded before Benefit Design Lines.</description>
    <label>Formulary Product</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusOne02/src/classes/BOT_DrugAccessDashboard_Extn.cls
public with sharing class BOT_DrugAccessDashboard_Extn 
{
    public Id accountId {get;set;}
    public List<BOT_Drug_Access__c> lstDrugAccess {get;set;}
    //public List<Formulary_Products_vod__c> lstFormularyProduct {get;set;}
    public Set<String> setMarkets = new Set<String>();
    //public Set<String> setDrugs = new Set<String>();
    public String selectedMarket {get;set;}
    //public Map<String, List<BOT_Drug_Access__c>> dataMap {get;set;}
    //public List<Decimal> drugAccessPercent {get;set;}
    public Boolean renderChart {get;set;}
    //Controller
    public BOT_DrugAccessDashboard_Extn(ApexPages.StandardController controller)
    {
        accountId = controller.getId();
        selectedMarket = 'immunology';
        //renderChart = true;
        lstDrugAccess = [SELECT Id, Name FROM BOT_Drug_Access__c WHERE BOT_Account__c =: accountId ORDER BY Name];
        for(BOT_Drug_Access__c objDrugAccess : lstDrugAccess)
        {
        	setMarkets.add(objDrugAccess.Name);
        }
        
        marketFilterRetrieve();
    }

    public void marketFilterRetrieve()
    {
        if(selectedMarket == '--ALL--' || selectedMarket == Null)
        {
            renderChart = true;
        }
        else
        {
            renderChart = false;
        }
    }

    public List<selectOption> getDynamicList()
    {
        List<selectOption> options = new List<selectOption>();
        if(setMarkets.size()>0 && setMarkets != null)
        {
            for(String c : setMarkets)
        	{
        		options.add(new selectOption(c,c));
        	}
            if(setMarkets.size()>1)
        	{
        		options.add(new selectOption('--ALL--','--ALL--'));
        	}
        }
        return options;
    }
}