BusOne02/src/objects/Veeva_Settings_vod__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Account_Plan_Sharing_vod__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enables automatic sharing of Account Plan related data to Team Members. See documentation for more details.
            0 - Disabled (default value)
            1 - Enabled</description>
        <label>Account Plan Sharing</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Veeva Settings</label>
</CustomObject>

BusOne02/src/classes/VeevaKamUtils.cls
public without sharing class VeevaKamUtils {

    public static boolean isVeevaAccountPlanShareEnabled() {
        Veeva_Settings_vod__c vsc = Veeva_Settings_vod__c.getOrgDefaults();
        if(vsc == null || vsc.Account_Plan_Sharing_vod__c == null || vsc.Account_Plan_Sharing_vod__c.intValue() != 1) {
            return false;
        }
        return true;
    }


    public static Set<Id> getInactiveUserIds(Set<Id> userIds) {
        Map<ID,User> userObjectsMap = new Map<Id, User>([Select Id, IsActive from User where IsActive = false AND Id IN : userIds]);
        return userObjectsMap.keySet();
    }


}